apiVersion: v1
kind: ConfigMap
data:
  LOGGING_LEVEL: "INFO"
  APP_NAME: {{ .Values.appname }}
  PROMETHEUS_PORT: "9600"
  SCOPE_KEYS: plant,edge,line,workload
  SCOPE_VALUES: {{ .Values.scopevalues }}
  SERVER_ADDR: "{{ .Values.serveraddr }}"
metadata:
  labels: {{ .Values.labels | toYaml | nindent 4 }}
  name: mythicalquality-config
