apiVersion: v1
kind: Service
metadata:
  name: mythicalqualitysvc
  namespace: mq-ns
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    pod: qualityserver

