# Default values for mqtt5qos1pubsub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mythicalanoy.azurecr.io/e4k
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.3"

nameOverride: ""
appname: "mythicalqualityserver"

annotations: {        
  prometheus.io/scrape: "true",
  prometheus.io/scheme: "http",
  prometheus.io/path: "/",
  prometheus.io/port: "9600",  
}

labels: {
  app: "mythicalqualityserver",
  appversion: "0.0.3",
  environment: "DEV",
  line: "FM407",
  plant: "MYTHICALSURFACE"
}

selectorLabels: {
  app: "mythicalqualityserver",
  appversion: "0.0.3",
  environment: "DEV",
  line: "FM407",
  plant: "MYTHICALSURFACE"
}

scopevalues: "FLOWERMOUND,MYTHICALNUC,FM407,MYTHICALSURFACE"
serveraddr: "50051"

service: {
  port: "50051",
  type: "LoadBalancer"
}
